let data=[];const $=x=>document.getElementById(x),money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0),num=x=>Number(String(x??'').replace(/,/g,''))||0,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view))});
function parseCSV(t){let rows=[],row=[],cell='',q=false;for(let i=0;i<t.length;i++){let c=t[i];if(c==='"'){if(q&&t[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&t[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(rows.length<2)return[];let h=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]||'').trim()]))) }
function normalize(r){let get=(...ks)=>{for(let k of ks){let hit=Object.keys(r).find(x=>x.toLowerCase().replace(/[^a-z]/g,'')===k.toLowerCase().replace(/[^a-z]/g,''));if(hit)return r[hit]}return''};return{symbol:get('Symbol','Ticker','NSE Code').toUpperCase().replace('.NS',''),company:get('Company','Name')||get('Symbol'),qty:num(get('Quantity','Qty')),avg:num(get('AvgPrice','Average Price','Buy Price')),sector:get('Sector','Industry')||'Unclassified',pe:num(get('PE','P/E')),roe:num(get('ROE')),roce:num(get('ROCE')),de:num(get('DebtEquity','Debt to Equity')),rg:num(get('RevenueGrowth','Sales Growth')),pg:num(get('ProfitGrowth','Profit Growth')),vol:num(get('Volatility','Beta')),price:num(get('CurrentPrice','Current Price','LTP'))}}
function calc(s){let invested=s.qty*s.avg,value=s.qty*s.price,pl=value-invested,ret=invested?pl/invested*100:0;let profitability=Math.min(25,Math.max(0,s.roe*.6+s.roce*.4));let growth=Math.min(25,Math.max(0,(s.rg+s.pg)/2+8));let leverage=s.de<=.3?15:s.de<=.7?12:s.de<=1.2?8:s.de<=2?4:1;let valuation=!s.pe?8:s.pe<=18?18:s.pe<=28?15:s.pe<=40?10:5;let momentum=Math.min(17,Math.max(0,8+ret/5));let score=Math.round(Math.min(100,profitability+growth+leverage+valuation+momentum));let grade=score>=80?'A':score>=68?'B':score>=55?'C':score>=42?'D':'E';let risk=(s.vol>=1.35||s.de>1.2)?'High':((!s.vol||s.vol<=1.05)&&s.de<=.8?'Low':'Moderate');let stable=(risk!=='High'&&score>=55&&s.de<=.8&&(!s.vol||s.vol<=1.10)&&s.rg>=0&&s.pg>=0);let bucket=(risk==='High'&&(s.pg>=18||s.rg>=18))?'High risk · High return':(score>=68&&(s.pg>=10||s.rg>=10))?'Quality growth':stable?'Stable / defensive':'Needs review';return{invested,value,pl,ret,score,grade,risk,bucket}}
function render(){let c=data.map(s=>({...s,...calc(s)})),inv=c.reduce((a,s)=>a+s.invested,0),mv=c.reduce((a,s)=>a+s.value,0),pl=mv-inv,avg=c.length?Math.round(c.reduce((a,s)=>a+s.score,0)/c.length):0;$('invested').textContent=money(inv);$('market').textContent=money(mv);$('pl').textContent=money(pl);$('pl').className=pl>=0?'pos':'neg';$('plp').textContent=inv?`${(pl/inv*100).toFixed(1)}%`:'0.0%';$('rating').textContent=!c.length?'—':avg>=80?'A':avg>=68?'B':avg>=55?'C':avg>=42?'D':'E';$('score').textContent=c.length?`${avg}/100 weighted research view`:'No data';
let sectors={};c.forEach(s=>sectors[s.sector]=(sectors[s.sector]||0)+s.value);$('allocation').classList.toggle('empty',!c.length);$('allocation').innerHTML=c.length?Object.entries(sectors).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="barrow"><b>${esc(k)}</b><div class="track"><i style="width:${mv?v/mv*100:0}%"></i></div><span>${mv?(v/mv*100).toFixed(1):0}%</span></div>`).join(''):'Import a CSV to see allocation.';
let high=c.filter(s=>s.risk==='High').length,prof=c.filter(s=>s.ret>0).length;$('profile').className='profile';$('profile').innerHTML=c.length?`<div class="line"><span>Holdings</span><b>${c.length}</b></div><div class="line"><span>Profitable positions</span><b>${prof}/${c.length}</b></div><div class="line"><span>High-risk positions</span><b>${high}/${c.length}</b></div><div class="line"><span>Average research score</span><b>${avg}/100</b></div>`:'Risk and return characteristics will appear here.';
let buckets=['High risk · High return','Quality growth','Stable / defensive','Needs review'];$('buckets').innerHTML=buckets.map(b=>{let names=c.filter(s=>s.bucket===b).map(s=>`<span class="stockchip">${esc(s.symbol)}</span>`).join('');return `<div><b>${b}</b><p class="stocklist">${names||'<span class="none">None</span>'}</p></div>`}).join('');
let strongest=c.slice().sort((a,b)=>b.score-a.score).slice(0,3), review=c.filter(s=>s.bucket==='Needs review').sort((a,b)=>a.score-b.score).slice(0,3), concentrated=mv?Math.max(0,...c.map(s=>s.value/mv*100)):0, topGainer=c.slice().sort((a,b)=>b.ret-a.ret)[0], topLoser=c.slice().sort((a,b)=>a.ret-b.ret)[0];let rec=[];if(c.length){if(topGainer)rec.push(`<div class="market-callout gainer"><b>Top gainer</b><p>${esc(topGainer.symbol)} is the strongest position by return at <strong>+${topGainer.ret.toFixed(1)}%</strong> versus its imported average cost.</p></div>`);if(topLoser)rec.push(`<div class="market-callout loser"><b>Top loser</b><p>${esc(topLoser.symbol)} is the weakest position by return at <strong>${topLoser.ret.toFixed(1)}%</strong> versus its imported average cost.</p></div>`);if(strongest.length)rec.push(`<div><b>Higher-scoring holdings</b><p>${strongest.map(s=>`${esc(s.symbol)} (${s.grade} · ${s.score})`).join(', ')} currently rank highest under Growfolio’s rule-based model.</p></div>`);if(review.length)rec.push(`<div><b>Review list</b><p>${review.map(s=>esc(s.symbol)).join(', ')} fall into the Needs review bucket based on the supplied fundamentals, risk inputs and position performance.</p></div>`);if(concentrated>30)rec.push(`<div><b>Concentration</b><p>Your largest holding represents ${concentrated.toFixed(1)}% of market value. Consider whether that concentration matches your intended risk exposure.</p></div>`);else rec.push(`<div><b>Diversification</b><p>No single holding exceeds 30% of current market value based on the imported portfolio.</p></div>`);rec.push(`<div><b>Growfolio suggests reviewing</b><p>Compare high-risk positions, weak fundamental scores and portfolio concentration before making any investment decision. Ratings are research signals, not buy/sell instructions.</p></div>`)}$('recommendation').className=c.length?'recommendation-body':'recommendation-body empty';$('recommendation').innerHTML=c.length?rec.join(''):'Import a CSV to generate portfolio observations.';
let tips=[];if(c.length){let gainers=c.filter(s=>s.ret>0).sort((a,b)=>b.ret-a.ret), weak=c.slice().sort((a,b)=>a.score-b.score);if(gainers[0])tips.push(`<div class="suggestion-item"><span>01</span><div><b>Review your strongest position</b><p>${esc(gainers[0].symbol)} has the highest portfolio return at ${gainers[0].ret.toFixed(1)}%. Compare its current weight with your intended allocation before changing the position.</p></div></div>`);else tips.push(`<div class="suggestion-item"><span>01</span><div><b>Review portfolio drawdown</b><p>No imported holding is currently above its average cost. Review position sizing and the underlying fundamentals before making changes.</p></div></div>`);if(weak[0])tips.push(`<div class="suggestion-item"><span>02</span><div><b>Re-check the lowest research score</b><p>${esc(weak[0].symbol)} has the lowest Growfolio score at ${weak[0].score}/100 (${weak[0].grade}). Review the supplied growth, leverage, valuation and risk inputs.</p></div></div>`)}$('suggestions').className=c.length?'suggestion-body':'suggestion-body empty';$('suggestions').innerHTML=c.length?tips.join(''):'Import a CSV to see two suggestions.';
$('rows').innerHTML=c.length?c.map(s=>`<tr><td><span class="ticker">${esc(s.symbol)}</span><span class="company">${esc(s.company)}</span></td><td>${s.qty}</td><td>${money(s.avg)}</td><td>${s.price?money(s.price):'—'}</td><td>${money(s.value)}</td><td class="${s.pl>=0?'pos':'neg'}">${money(s.pl)}<span class="company">${s.ret.toFixed(1)}%</span></td><td><span class="pill">${s.risk}</span></td><td><span class="pill">${s.grade} · ${s.score}</span></td></tr>`).join(''):'<tr><td colspan="8" class="emptycell">Import a portfolio CSV to begin.</td></tr>';
$('ratingcards').innerHTML=c.length?c.map(s=>`<article class="card ratingcard"><div class="top"><div><b>${esc(s.symbol)}</b><span class="company">${esc(s.company)}</span></div><div class="grade">${s.grade}</div></div><div class="scorebar"><i style="width:${s.score}%"></i></div><div class="metrics"><div><span>Score</span><b>${s.score}/100</b></div><div><span>Risk</span><b>${s.risk}</b></div><div><span>ROE</span><b>${s.roe?s.roe.toFixed(1)+'%':'—'}</b></div><div><span>Debt / Equity</span><b>${s.de||'—'}</b></div><div><span>Profit growth</span><b>${s.pg?s.pg.toFixed(1)+'%':'—'}</b></div><div><span>P/E</span><b>${s.pe||'—'}</b></div></div><p class="why">${s.bucket}. Rating combines profitability, growth, leverage, valuation and position performance from the supplied/latest available data.</p></article>`).join(''):'<div class="card empty">Ratings appear after import.</div>'}
async function loadFile(f){let rows=parseCSV(await f.text()).map(normalize).filter(x=>x.symbol&&x.qty);if(!rows.length){toast('CSV format not recognized');return}data=rows;localStorage.setItem('growfolio_data',JSON.stringify(data));$('status').innerHTML=`Loaded <b>${data.length}</b> holdings from <b>${esc(f.name)}</b>. ${data.some(x=>x.price)?'CSV prices are being used until refreshed.':'No current prices found; use Refresh prices.'}`;render();toast('Portfolio imported')}
$('csv').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);$('csv2').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);
$('refresh').onclick=async()=>{if(!data.length)return toast('Import a CSV first');$('refresh').textContent='Refreshing…';let ok=0;for(let s of data){try{let u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s.symbol+'.NS')}?interval=1d&range=1d`;let r=await fetch(u);if(!r.ok)throw 0;let j=await r.json(),p=j?.chart?.result?.[0]?.meta?.regularMarketPrice;if(p){s.price=Number(p);ok++}}catch(e){}}localStorage.setItem('growfolio_data',JSON.stringify(data));render();$('refresh').textContent='Refresh prices';$('status').innerHTML=ok?`Updated <b>${ok}/${data.length}</b> prices from the latest quote response. Browser-accessible public quote endpoints can be intermittent.`:`Could not refresh prices in this browser. Existing CSV prices were retained. For reliable deployment, connect a licensed data API through a serverless proxy.`;toast(ok?`${ok} prices updated`:'Live quote request unavailable')};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
try{data=JSON.parse(localStorage.getItem('growfolio_data')||'[]')}catch{}render();

const PAYMENT_LINK='';
function openPayment(){if(PAYMENT_LINK){window.open(PAYMENT_LINK,'_blank','noopener')}else{toast('Add your Razorpay/Stripe payment link in PAYMENT_LINK inside app.js')}}
['pay99','paySuggestions','payOverview'].forEach(id=>{const b=document.getElementById(id);if(b)b.onclick=openPayment});
